name: dxsp01
version: 1.0.0
profile: dxsp01
config-version: 2

model-paths:
  - models
seed-paths:
  - seeds
test-paths:
  - tests
analysis-paths:
  - analyses
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_packages
  - logs
models:
    test:
      +materialized: view  
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    mart:
      +materialized: table
vars:
  data_start_date: 2024-01-01
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: metaplane/dbt_expectations
    version:
      - ">=0.10.0"
      - <0.11.0
require-dbt-version: ">=1.7.0"
data_tests:
  +severity: warn