services:

  # db:
  #   image: postgres:13
  #   container_name: dx01_db_postgres
  #   environment:
  #     POSTGRES_USER: airbyte
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: airbyte
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - sp_bridge_001

  # temporal:
  #   image: temporalio/auto-setup:1.20.1
  #   container_name: dx01_temporal
  #   volumes:
  #     - ./temporal/config:/etc/temporal/config  # 改為這個路徑
  #   environment:
  #     CONFIG_DIR: /etc/temporal/config  # 確保這與上面的路徑一致
  #   ports:
  #     - "7233:7233"
  #   depends_on:
  #     - db
  #   networks:
  #     sp_bridge_001:
  #       aliases:
  #         - airbyte-temporal  # 確保這個別名存在

  # airbyte:
  #   build:
  #     context: ./airbyte
  #     dockerfile: Dockerfile
  #   image: dx01_extract_airbyte
  #   container_name: dx01_extract_airbyte
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./airbyte/workspace:/data/workspace
  #     - ./airbyte/local_root:/data/local_root
  #     - ./airbyte/logs:/data/logs
  #     - ./airbyte/config:/config
  #     - ./airbyte/credentials:/secrets:ro
  #   environment:
  #     TEMPORAL_HOST: airbyte-temporal:7233
  #     DATABASE_HOST: dx01_db_postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_DB: airbyte
  #     DATABASE_USER: airbyte
  #     DATABASE_PASSWORD: password
  #     DATABASE_URL: jdbc:postgresql://dx01_db_postgres:5432/airbyte?user=airbyte&password=password
  #     AIRBYTE_VERSION: 0.50.4
  #     AIRBYTE_ROLE: server
  #     AIRBYTE_WORKSPACE_ROOT: /data/workspace
  #     AIRBYTE_DATA_PLANE_LOCAL_ROOT: /data/local_root
  #     AIRBYTE_LOGS_ROOT: /data/logs
  #     GOOGLE_APPLICATION_CREDENTIALS: /secrets/bq-dxsp01-credentials-20250416.json
  #   depends_on:
  #     - db
  #     - temporal
  #   networks:
  #     - sp_bridge_001
  #   restart: unless-stopped

  # airbyte-webapp:
  #   image: airbyte/webapp:0.50.4
  #   container_name: dx01_web_airbyte
  #   environment:
  #     AIRBYTE_API_HOST: http://dx01_extract_airbyte:8001
  #     INTERNAL_API_HOST: dx01_extract_airbyte:8001
  #     CONNECTOR_BUILDER_API_HOST: dx01_extract_airbyte:8001
  #     TRACKING_STRATEGY: segment
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - airbyte
  #   networks:
  #     - sp_bridge_001

  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    image: dx01_dm_dbt
    container_name: dx01_dm_dbt
    volumes:
      - ./dbt:/usr/app
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml:ro
      - ./dbt/credentials/bq-dxsp01-credentials-20250416.json:/usr/app/credentials/bq-dxsp01-credentials-20250416.json:ro
    working_dir: /usr/app
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /usr/app/credentials/bq-dxsp01-credentials-20250416.json
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "8081:8081"
    # networks:
    #   - sp_bridge_001

# networks:
#   sp_bridge_001:
#     driver: bridge
