services:

  # 儲存metadata
  # db:
  #   image: postgres:13
  #   container_name: dx01_db_postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./docker/postgres/data:/var/lib/postgresql/data
  #   networks:
  #     - sp_bridge_001

  # data modeling tool
  dbt:
    build:
      context: ./docker/dbt
      dockerfile: Dockerfile
    image: dx01_dm_dbt
    container_name: dx01_dm_dbt
    volumes:
      - ./docker/dbt:/usr/app
      - ./docker/dbt/profiles.yml:/root/.dbt/profiles.yml:ro
      - ./docker/dbt/credentials/dx01_gcp_credentials_20250416.json:/usr/app/credentials/dx01_gcp_credentials_20250416.json:ro
    working_dir: /usr/app
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /usr/app/credentials/dx01_gcp_credentials_20250416.json
    entrypoint: ["sh", "-c", "dbt docs generate && dbt docs serve --port 8081 --host 0.0.0.0"]
    ports:
      - "8081:8081"
    networks:
      - sp_bridge_001

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - sp_bridge_001

  # data viz tool
  superset:
    build:
      context: ./docker/superset
      dockerfile: Dockerfile
    env_file:
      - .env
    image: dx01_viz_superset
    container_name: dx01_viz_superset
    environment:
      - SUPERSET_ENV=${SUPERSET_ENV}
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/dx01_gcp_credentials_20250416.json
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/superset/home:/app/superset_home
      - ./docker/superset/config:/app/config
      - ./docker/superset/credentials/dx01_gcp_credentials_20250416.json:/app/credentials/dx01_gcp_credentials_20250416.json:ro
    ports:
      - "8088:8088"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - sp_bridge_001
    depends_on:
      - postgres
    # http://127.0.0.1:8088
    # 登錄前需先執行docker exec -it dx01_viz_superset superset fab create-admin --username rex --password dx01
    # -> docker exec -it dx01_viz_superset superset db upgrade
      # -> docker exec -it dx01_viz_superset superset init


networks:
  sp_bridge_001:
    driver: bridge
