name: dx01
version: 1.0.0
profile: dx01
config-version: 2

# model-paths
model-paths:
  - models
seed-paths:
  - seeds
test-paths:
  - tests
analysis-paths:
  - analyses
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_packages
  - logs
models:
  dx01:
    dx01:
      test:
        +materialized: view 
        +schema: dx01_test
      staging:
        +materialized: view
        +schema: dx01_stg
      intermediate:
        +materialized: table
        +schema: dx01_int
      mart:
        +materialized: table
        +schema: dx01_mrt
vars:
  data_start_date: 2024-01-01
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: metaplane/dbt_expectations
    version:
      - ">=0.10.0"
      - <0.11.0
require-dbt-version: ">=1.7.0"
data_tests:
  +severity: warn